---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-5.10-i386

suites:
  - name: client
    run_list:
      - recipe[syslog-ng::client]
    attributes:
      env_name: integration
      app_name: testing
      syslog_ng:
        use_tls: false
        user: 'root'
        group: 'root'
        port_private: '1028'
  - name: server
    run_list:
      - recipe[syslog-ng::server]
    attributes:
      env_name: integration
      app_name: testing
      syslog_ng:
        use_tls: false
        user: 'root'
        group: 'root'
        port_private: '1028'
        port_public: '1029'
